package com.makar.tacticaltablet.game.lifecycle;

public enum MatchStartStep {
    RESET_TRANSIENT_RUNTIME,
    CONFIGURE_TEAMS,
    RESET_AIRDROP_SCHEDULER,
    START_DISCORD_TRACKING,
    START_CONTRACTS,
    RESET_MATCH_COUNTERS,
    EXECUTE_START_DATAPACK,
    ANNOUNCE_MAP_START,
    ENFORCE_GAME_RULES,
    START_ZONE,
    PREPARE_SAFE_TELEPORT,
    INITIALIZE_PLAYERS,
    START_VOICE_MATCH,
    CAPTURE_PARTICIPANTS,
    START_EXTRACTION,
    SYNC_CLASS_XP,
    SET_LEGACY_RUNNING
}
